[package]
name = "simple"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
omegalul = {path = "../.."}

tokio = { version = "1.19.2", features = ["full"] }
futures = "0.3.21"